### ISSUE TITLE
[UI] Navbar Implementation

### ISSUE THREAD

**Issue by Khadeeejah** [Khadeeejah/celo-africa-dao#2]
Implement the Navbar from the Figma design below and make it responsive 

[Figma Design](https://www.figma.com/file/2sTdJLgI7Jl4o5vpR6VZSg/CELO-DAO?type=design&node-id=270-917&t=3UdHmdJkNWSlZICg-4)

**Comment by Mentor-Ntech** [comment]
Hi khadeeejah
I’ll like to work on this
