### ISSUE TITLE
[UI] About Section

### ISSUE THREAD

**Issue by Khadeeejah** [Khadeeejah/celo-africa-dao#4]
Implement the About Section and make it responsive

[figma Design](https://www.figma.com/file/2sTdJLgI7Jl4o5vpR6VZSg/CELO-DAO?type=design&node-id=126-522&t=uSaRuR8sCrl9Fvdo-4)

N.B 
![Hands Coin](https://github.com/Khadeeejah/celo-africa-dao/assets/52764879/abdc13c8-e125-4cd0-8c2b-7f89eeeeec62)
This svg is animated

**Comment by khaddyBola** [comment]
Hi, this is Khadijah 
I will like to work on this
