### ISSUE TITLE
[UI] Vision and Mission Section

### ISSUE THREAD

**Issue by Khadeeejah** [Khadeeejah/celo-africa-dao#5]
Implement this section and make it responsive
[figma design](https://www.figma.com/file/2sTdJLgI7Jl4o5vpR6VZSg/CELO-DAO?type=design&node-id=126-494&t=uSaRuR8sCrl9Fvdo-4)

**Comment by khaddyBola** [comment]
Hi, Khadijah
I will work on this

**Comment by khaddyBola** [comment]
@Khadeeejah, The background Image has been attach now, Kindly review
