### ISSUE TITLE
[UI] Featured Article Section

### ISSUE THREAD

**Issue by Khadeeejah** [Khadeeejah/celo-africa-dao#6]
Implement this section and make it responsive
- You should be able to toggle between three tabs , which are Blogs, events and videos
- The **see more** button should be linked to the official Celo Africa DAO blog.

[Figma Design](https://www.figma.com/file/2sTdJLgI7Jl4o5vpR6VZSg/CELO-DAO?type=design&node-id=314-1151&t=uSaRuR8sCrl9Fvdo-4)
[Blog](https://celoafricadao.hashnode.dev/)

**Comment by DevBigEazi** [comment]
Hello @Khadeeejah, pls I will like to work on this issue
