### ISSUE TITLE
[UI] FooterSection

### ISSUE THREAD

**Issue by Khadeeejah** [Khadeeejah/celo-africa-dao#9]
Implement the design and make it responsive
- Use Javascript to implement the copyright section
[Figma Design](https://www.figma.com/file/2sTdJLgI7Jl4o5vpR6VZSg/CELO-DAO?type=design&node-id=270-942&t=uSaRuR8sCrl9Fvdo-4)

**Comment by DevBigEazi** [comment]
Hi, this is Isiaq. I will like to work on the footer as seen through the design link here. You named this issue Faq which I think might be a mistake.

**Comment by Khadeeejah** [comment]
hi @DevBigEazi  thank you for noting that, i have fixed it already
